// apps/examples-vue/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import { CButton } from '@componentry-ui/vue'

const focusTargetRef = ref<HTMLElement | null>(null)
const eventLog = ref('—')
const clickLog = ref('—')
</script>

<template>
  <main style="padding: 2rem; font-family: sans-serif;">
    <h1>Componentry — Vue: All CButton Usages</h1>

    <!-- ── 1. VARIANTS ──────────────────────────────────────────── -->
    <section style="margin-bottom: 2rem;">
      <h2 style="font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; color: #888;">1. Variants</h2>
      <div style="display: flex; flex-wrap: wrap; gap: 0.5rem;">
        <CButton variant="default">Default</CButton>
        <CButton variant="primary">Primary</CButton>
        <CButton variant="success">Success</CButton>
        <CButton variant="neutral">Neutral</CButton>
        <CButton variant="warning">Warning</CButton>
        <CButton variant="danger">Danger</CButton>
        <CButton variant="text">Text</CButton>
      </div>
    </section>

    <!-- ── 2. SIZES ─────────────────────────────────────────────── -->
    <section style="margin-bottom: 2rem;">
      <h2 style="font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; color: #888;">2. Sizes</h2>
      <div style="display: flex; flex-wrap: wrap; gap: 0.5rem; align-items: center;">
        <CButton size="small">Small</CButton>
        <CButton size="medium">Medium</CButton>
        <CButton size="large">Large</CButton>
      </div>
    </section>

    <!-- ── 3. OUTLINED ──────────────────────────────────────────── -->
    <section style="margin-bottom: 2rem;">
      <h2 style="font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; color: #888;">3. Outlined</h2>
      <div style="display: flex; flex-wrap: wrap; gap: 0.5rem;">
        <CButton variant="default" :outline="true">Default</CButton>
        <CButton variant="primary" :outline="true">Primary</CButton>
        <CButton variant="success" :outline="true">Success</CButton>
        <CButton variant="neutral" :outline="true">Neutral</CButton>
        <CButton variant="warning" :outline="true">Warning</CButton>
        <CButton variant="danger" :outline="true">Danger</CButton>
      </div>
    </section>

    <!-- ── 4. PILL ──────────────────────────────────────────────── -->
    <section style="margin-bottom: 2rem;">
      <h2 style="font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; color: #888;">4. Pill</h2>
      <div style="display: flex; flex-wrap: wrap; gap: 0.5rem; align-items: center;">
        <CButton variant="primary" :pill="true">Primary Pill</CButton>
        <CButton variant="success" :pill="true" :outline="true">Outline Pill</CButton>
        <CButton variant="danger" :pill="true" size="small">Small Pill</CButton>
        <CButton variant="neutral" :pill="true" size="large">Large Pill</CButton>
      </div>
    </section>

    <!-- ── 5. CIRCLE ────────────────────────────────────────────── -->
    <section style="margin-bottom: 2rem;">
      <h2 style="font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; color: #888;">5. Circle (icon buttons)</h2>
      <div style="display: flex; flex-wrap: wrap; gap: 0.5rem; align-items: center;">
        <CButton :circle="true" variant="default">✕</CButton>
        <CButton :circle="true" variant="primary">★</CButton>
        <CButton :circle="true" variant="danger" size="small">🗑</CButton>
        <CButton :circle="true" variant="success" size="large">✓</CButton>
        <CButton :circle="true" variant="neutral" :outline="true">⚙</CButton>
      </div>
    </section>

    <!-- ── 6. CARET ─────────────────────────────────────────────── -->
    <section style="margin-bottom: 2rem;">
      <h2 style="font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; color: #888;">6. Caret</h2>
      <div style="display: flex; flex-wrap: wrap; gap: 0.5rem;">
        <CButton :caret="true">Default + Caret</CButton>
        <CButton variant="primary" :caret="true">Primary + Caret</CButton>
        <CButton variant="neutral" :caret="true" :outline="true">Outline + Caret</CButton>
        <CButton variant="warning" :caret="true" :pill="true">Pill + Caret</CButton>
      </div>
    </section>

    <!-- ── 7. LOADING ───────────────────────────────────────────── -->
    <section style="margin-bottom: 2rem;">
      <h2 style="font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; color: #888;">7. Loading</h2>
      <div style="display: flex; flex-wrap: wrap; gap: 0.5rem;">
        <CButton :loading="true">Default</CButton>
        <CButton :loading="true" variant="primary">Primary</CButton>
        <CButton :loading="true" variant="danger" :outline="true">Outline</CButton>
        <CButton :loading="true" variant="success" :pill="true">Pill</CButton>
        <CButton :loading="true" :circle="true" variant="neutral">★</CButton>
      </div>
    </section>

    <!-- ── 8. DISABLED ──────────────────────────────────────────── -->
    <section style="margin-bottom: 2rem;">
      <h2 style="font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; color: #888;">8. Disabled</h2>
      <div style="display: flex; flex-wrap: wrap; gap: 0.5rem;">
        <CButton :disabled="true">Default</CButton>
        <CButton :disabled="true" variant="primary">Primary</CButton>
        <CButton :disabled="true" variant="success" :outline="true">Outline</CButton>
        <CButton :disabled="true" variant="danger" :pill="true">Pill</CButton>
        <CButton :disabled="true" :circle="true">✕</CButton>
      </div>
    </section>

    <!-- ── 9. PREFIX SLOT ───────────────────────────────────────── -->
    <section style="margin-bottom: 2rem;">
      <h2 style="font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; color: #888;">9. Prefix slot</h2>
      <div style="display: flex; flex-wrap: wrap; gap: 0.5rem;">
        <CButton variant="primary">
          <span slot="prefix">⬇</span>
          Download
        </CButton>
        <CButton variant="success">
          <span slot="prefix">✓</span>
          Confirm
        </CButton>
        <CButton variant="danger" :outline="true">
          <span slot="prefix">🗑</span>
          Delete
        </CButton>
      </div>
    </section>

    <!-- ── 10. SUFFIX SLOT ──────────────────────────────────────── -->
    <section style="margin-bottom: 2rem;">
      <h2 style="font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; color: #888;">10. Suffix slot</h2>
      <div style="display: flex; flex-wrap: wrap; gap: 0.5rem;">
        <CButton variant="primary">
          Next
          <span slot="suffix">→</span>
        </CButton>
        <CButton variant="neutral" :outline="true">
          Share
          <span slot="suffix">↗</span>
        </CButton>
      </div>
    </section>

    <!-- ── 11. PREFIX + SUFFIX ──────────────────────────────────── -->
    <section style="margin-bottom: 2rem;">
      <h2 style="font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; color: #888;">11. Prefix + Suffix</h2>
      <div style="display: flex; flex-wrap: wrap; gap: 0.5rem;">
        <CButton variant="primary">
          <span slot="prefix">📁</span>
          Open File
          <span slot="suffix">↗</span>
        </CButton>
        <CButton variant="warning" :outline="true">
          <span slot="prefix">⚠</span>
          Review
          <span slot="suffix">→</span>
        </CButton>
      </div>
    </section>

    <!-- ── 12. LINK BUTTON ──────────────────────────────────────── -->
    <section style="margin-bottom: 2rem;">
      <h2 style="font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; color: #888;">12. Link button (href)</h2>
      <div style="display: flex; flex-wrap: wrap; gap: 0.5rem;">
        <CButton href="https://example.com" target="_blank">Open Link</CButton>
        <CButton href="https://example.com" target="_blank" variant="primary">
          <span slot="prefix">↗</span>
          External Link
        </CButton>
        <CButton href="/file.pdf" download="report.pdf" variant="success">Download PDF</CButton>
        <CButton href="https://example.com" :disabled="true" variant="neutral">Disabled Link</CButton>
      </div>
    </section>

    <!-- ── 13. FORM TYPES ───────────────────────────────────────── -->
    <section style="margin-bottom: 2rem;">
      <h2 style="font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; color: #888;">13. Form types</h2>
      <div style="display: flex; flex-wrap: wrap; gap: 0.5rem; align-items: center;">
        <form @submit.prevent="clickLog = 'Form submitted!'">
          <CButton type="submit" variant="primary" name="action" value="save">
            Submit Form
          </CButton>
        </form>
        <form style="display: flex; gap: 0.5rem; align-items: center;">
          <input type="text" value="clear me" style="padding: 0.25rem 0.5rem;" />
          <CButton type="reset" variant="neutral">Reset Form</CButton>
        </form>
        <CButton type="button">Plain Button</CButton>
      </div>
    </section>

    <!-- ── 14. TOOLTIP ──────────────────────────────────────────── -->
    <section style="margin-bottom: 2rem;">
      <h2 style="font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; color: #888;">14. Tooltip</h2>
      <div style="display: flex; flex-wrap: wrap; gap: 0.5rem;">
        <CButton tooltip="This saves your progress" variant="primary">Save</CButton>
        <CButton tooltip="Permanently deletes the record" variant="danger" :circle="true">🗑</CButton>
      </div>
    </section>

    <!-- ── 15. ONCLICK ──────────────────────────────────────────── -->
    <section style="margin-bottom: 2rem;">
      <h2 style="font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; color: #888;">15. onClick / click handler</h2>
      <div style="display: flex; flex-wrap: wrap; gap: 0.5rem; align-items: center;">
        <!-- inline handler -->
        <CButton variant="primary" @click="clickLog = 'Primary clicked!'">
          Click me
        </CButton>

        <!-- method reference -->
        <CButton variant="success" @click="() => clickLog = 'Success clicked!'">
          Method ref
        </CButton>

        <!-- disabled — click should NOT fire -->
        <CButton variant="danger" :disabled="true" @click="clickLog = 'Should not fire'">
          Disabled click
        </CButton>

        <!-- loading — click should NOT fire -->
        <CButton variant="warning" :loading="true" @click="clickLog = 'Should not fire'">
          Loading click
        </CButton>

        <span style="color: #555; font-size: 0.9rem;">{{ clickLog }}</span>
      </div>
    </section>

    <!-- ── 16. EVENTS — cFocus / cBlur ─────────────────────────── -->
    <section style="margin-bottom: 2rem;">
      <h2 style="font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; color: #888;">16. cFocus / cBlur events</h2>
      <div style="display: flex; flex-wrap: wrap; gap: 0.5rem; align-items: center;">
        <CButton
          variant="primary"
          @c-focus="eventLog = 'cFocus fired'"
          @c-blur="eventLog = 'cBlur fired'"
        >
          Focus / Blur me
        </CButton>
        <span style="color: #555; font-size: 0.9rem;">{{ eventLog }}</span>
      </div>
    </section>

    <!-- ── 17. JS METHODS ───────────────────────────────────────── -->
    <section style="margin-bottom: 2rem;">
      <h2 style="font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; color: #888;">17. Imperative methods</h2>
      <div style="display: flex; flex-wrap: wrap; gap: 0.5rem; align-items: center;">
        <CButton ref="focusTargetRef" variant="primary">Focus target</CButton>
        <CButton variant="neutral" @click="(focusTargetRef as any)?.setFocus()">
          setFocus()
        </CButton>
        <CButton variant="neutral" @click="(focusTargetRef as any)?.removeFocus()">
          removeFocus()
        </CButton>
        <CButton variant="neutral" @click="(focusTargetRef as any)?.triggerClick()">
          triggerClick()
        </CButton>
      </div>
    </section>

    <!-- ── 18. COMBINED COMBOS ──────────────────────────────────── -->
    <section style="margin-bottom: 2rem;">
      <h2 style="font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; color: #888;">18. Combined combos</h2>
      <div style="display: flex; flex-wrap: wrap; gap: 0.5rem; align-items: center;">
        <CButton
          variant="primary"
          :pill="true"
          size="large"
          :caret="true"
          @click="clickLog = 'Deploy clicked!'"
        >
          <span slot="prefix">🚀</span>
          Deploy
        </CButton>

        <CButton variant="danger" :outline="true" :pill="true" size="small" :loading="true">
          Deleting…
        </CButton>

        <CButton
          variant="success"
          :circle="true"
          size="large"
          tooltip="Approve"
          @click="clickLog = 'Approved!'"
        >
          ✓
        </CButton>

        <CButton variant="neutral" :outline="true" :caret="true" size="small" :disabled="true">
          Options
        </CButton>

        <CButton
          href="https://example.com"
          target="_blank"
          variant="primary"
          :pill="true"
          @click="clickLog = 'Link clicked!'"
        >
          <span slot="prefix">↗</span>
          External
          <span slot="suffix">★</span>
        </CButton>

        <span style="color: #555; font-size: 0.9rem;">{{ clickLog }}</span>
      </div>
    </section>
  </main>
</template>

// apps/examples-react/src/App.tsx
import { CButton } from "@componentry/react";
import React, { useRef, useState } from "react";

const Row = ({ children }: { children: React.ReactNode }) => (
  <div style={{ display: "flex", flexWrap: "wrap", alignItems: "center", gap: "0.5rem", marginBottom: "0.5rem" }}>
    {children}
  </div>
);

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <section style={{ marginBottom: "2rem" }}>
    <h2 style={{ fontSize: "0.8rem", textTransform: "uppercase", letterSpacing: "0.05em", color: "#888", marginBottom: "0.75rem" }}>
      {title}
    </h2>
    {children}
  </section>
);

export default function App() {
  const focusTargetRef = useRef<HTMLCButtonElement>(null);
  const [eventLog, setEventLog] = useState("—");
  const [clickCount, setClickCount] = useState(0);
  const [liked, setLiked] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [isDone, setIsDone] = useState(false);
  const [danger, setDanger] = useState(false);
  const [clickLog, setClickLog] = useState("—");

  const handleAsyncClick = () => {
    setIsLoading(true);
    setIsDone(false);
    setTimeout(() => {
      setIsLoading(false);
      setIsDone(true);
    }, 2000);
  };

  return (
    <main style={{ padding: "2rem", fontFamily: "sans-serif" }}>
      <h1>CButton — All Usages</h1>

      {/* ── 1. VARIANTS ─────────────────────────────────────────── */}
      <Section title="1. Variants">
        <Row>
          <CButton variant="default">Default</CButton>
          <CButton variant="primary">Primary</CButton>
          <CButton variant="success">Success</CButton>
          <CButton variant="neutral">Neutral</CButton>
          <CButton variant="warning">Warning</CButton>
          <CButton variant="danger">Danger</CButton>
          <CButton variant="text">Text</CButton>
        </Row>
      </Section>

      {/* ── 2. SIZES ────────────────────────────────────────────── */}
      <Section title="2. Sizes">
        <Row>
          <CButton size="small">Small</CButton>
          <CButton size="medium">Medium</CButton>
          <CButton size="large">Large</CButton>
        </Row>
      </Section>

      {/* ── 3. OUTLINED ─────────────────────────────────────────── */}
      <Section title="3. Outlined">
        <Row>
          <CButton variant="default" outline>Default</CButton>
          <CButton variant="primary" outline>Primary</CButton>
          <CButton variant="success" outline>Success</CButton>
          <CButton variant="neutral" outline>Neutral</CButton>
          <CButton variant="warning" outline>Warning</CButton>
          <CButton variant="danger" outline>Danger</CButton>
        </Row>
      </Section>

      {/* ── 4. PILL ─────────────────────────────────────────────── */}
      <Section title="4. Pill">
        <Row>
          <CButton variant="primary" pill>Primary Pill</CButton>
          <CButton variant="success" pill outline>Outline Pill</CButton>
          <CButton variant="danger" pill size="small">Small Pill</CButton>
          <CButton variant="neutral" pill size="large">Large Pill</CButton>
        </Row>
      </Section>

      {/* ── 5. CIRCLE ───────────────────────────────────────────── */}
      <Section title="5. Circle (icon buttons)">
        <Row>
          <CButton circle variant="default">✕</CButton>
          <CButton circle variant="primary">★</CButton>
          <CButton circle variant="danger" size="small">🗑</CButton>
          <CButton circle variant="success" size="large">✓</CButton>
          <CButton circle variant="neutral" outline>⚙</CButton>
        </Row>
      </Section>

      {/* ── 6. CARET ────────────────────────────────────────────── */}
      <Section title="6. Caret">
        <Row>
          <CButton caret>Default + Caret</CButton>
          <CButton variant="primary" caret>Primary + Caret</CButton>
          <CButton variant="neutral" caret outline>Outline + Caret</CButton>
          <CButton variant="warning" caret pill>Pill + Caret</CButton>
        </Row>
      </Section>

      {/* ── 7. LOADING ──────────────────────────────────────────── */}
      <Section title="7. Loading">
        <Row>
          <CButton loading>Default</CButton>
          <CButton loading variant="primary">Primary</CButton>
          <CButton loading variant="danger" outline>Outline</CButton>
          <CButton loading variant="success" pill>Pill</CButton>
          <CButton loading circle variant="neutral">★</CButton>
        </Row>
      </Section>

      {/* ── 8. DISABLED ─────────────────────────────────────────── */}
      <Section title="8. Disabled">
        <Row>
          <CButton disabled>Default</CButton>
          <CButton disabled variant="primary">Primary</CButton>
          <CButton disabled variant="success" outline>Outline</CButton>
          <CButton disabled variant="danger" pill>Pill</CButton>
          <CButton disabled circle>✕</CButton>
        </Row>
      </Section>

      {/* ── 9. PREFIX SLOT ──────────────────────────────────────── */}
      <Section title="9. Prefix slot">
        <Row>
          <CButton variant="primary">
            <span slot="prefix">⬇</span>
            Download
          </CButton>
          <CButton variant="success">
            <span slot="prefix">✓</span>
            Confirm
          </CButton>
          <CButton variant="danger" outline>
            <span slot="prefix">🗑</span>
            Delete
          </CButton>
        </Row>
      </Section>

      {/* ── 10. SUFFIX SLOT ─────────────────────────────────────── */}
      <Section title="10. Suffix slot">
        <Row>
          <CButton variant="primary">
            Next
            <span slot="suffix">→</span>
          </CButton>
          <CButton variant="neutral" outline>
            Share
            <span slot="suffix">↗</span>
          </CButton>
        </Row>
      </Section>

      {/* ── 11. PREFIX + SUFFIX ─────────────────────────────────── */}
      <Section title="11. Prefix + Suffix">
        <Row>
          <CButton variant="primary">
            <span slot="prefix">📁</span>
            Open File
            <span slot="suffix">↗</span>
          </CButton>
          <CButton variant="warning" outline>
            <span slot="prefix">⚠</span>
            Review
            <span slot="suffix">→</span>
          </CButton>
        </Row>
      </Section>

      {/* ── 12. LINK BUTTON ─────────────────────────────────────── */}
      <Section title="12. Link button (href)">
        <Row>
          <CButton href="https://example.com" target="_blank">
            Open Link
          </CButton>
          <CButton href="https://example.com" target="_blank" variant="primary">
            <span slot="prefix">↗</span>
            External Link
          </CButton>
          <CButton href="/file.pdf" download="report.pdf" variant="success">
            Download PDF
          </CButton>
          <CButton href="https://example.com" disabled variant="neutral">
            Disabled Link
          </CButton>
        </Row>
      </Section>

      {/* ── 13. FORM TYPES ──────────────────────────────────────── */}
      <Section title="13. Form types">
        <Row>
          <form onSubmit={(e) => { e.preventDefault(); setClickLog("Form submitted!"); }}
            style={{ display: "flex", gap: "0.5rem", alignItems: "center" }}>
            <CButton type="submit" variant="primary" name="action" value="save">
              Submit Form
            </CButton>
          </form>
          <form style={{ display: "flex", gap: "0.5rem", alignItems: "center" }}>
            <input type="text" defaultValue="clear me" style={{ padding: "0.25rem 0.5rem" }} />
            <CButton type="reset" variant="neutral">Reset Form</CButton>
          </form>
          <CButton type="button">Plain Button</CButton>
          <span style={{ fontSize: "0.85rem", color: "#555" }}>{clickLog}</span>
        </Row>
      </Section>

      {/* ── 14. TOOLTIP ─────────────────────────────────────────── */}
      <Section title="14. Tooltip">
        <Row>
          <CButton tooltip="This saves your progress" variant="primary">Save</CButton>
          <CButton tooltip="Permanently deletes the record" variant="danger" circle>🗑</CButton>
        </Row>
      </Section>

      {/* ── 15. BASIC CLICK ─────────────────────────────────────── */}
      <Section title="15. Basic onClick — alert">
        <Row>
          <CButton variant="primary" onClick={() => alert("Button clicked!")}>
            Click me
          </CButton>
        </Row>
      </Section>

      {/* ── 16. CLICK COUNTER ───────────────────────────────────── */}
      <Section title="16. onClick — update state (click counter)">
        <Row>
          <CButton variant="neutral" onClick={() => setClickCount((c) => c + 1)}>
            Clicked {clickCount} time{clickCount !== 1 ? "s" : ""}
          </CButton>
          <CButton variant="text" onClick={() => setClickCount(0)}>Reset</CButton>
        </Row>
      </Section>

      {/* ── 17. TOGGLE ──────────────────────────────────────────── */}
      <Section title="17. onClick — toggle variant (like button)">
        <Row>
          <CButton variant={liked ? "success" : "default"} onClick={() => setLiked((l) => !l)}>
            {liked ? "❤️ Liked" : "🤍 Like"}
          </CButton>
        </Row>
      </Section>

      {/* ── 18. ASYNC / LOADING ─────────────────────────────────── */}
      <Section title="18. onClick — async action with loading state">
        <Row>
          <CButton
            variant={isDone ? "success" : "primary"}
            loading={isLoading}
            disabled={isLoading}
            onClick={handleAsyncClick}
          >
            {isDone ? "✓ Done!" : "Save Changes"}
          </CButton>
          {isDone && (
            <CButton variant="text" onClick={() => setIsDone(false)}>Reset</CButton>
          )}
        </Row>
      </Section>

      {/* ── 19. CONFIRM BEFORE ACTION ───────────────────────────── */}
      <Section title="19. onClick — confirm before destructive action">
        <Row>
          <CButton
            variant="danger"
            onClick={() => {
              if (window.confirm("Are you sure you want to delete this?")) {
                alert("Deleted!");
              }
            }}
          >
            <span slot="prefix">🗑</span>
            Delete
          </CButton>
        </Row>
      </Section>

      {/* ── 20. DISABLED DOES NOT FIRE ──────────────────────────── */}
      <Section title="20. disabled — onClick does not fire">
        <Row>
          <CButton variant="primary" disabled onClick={() => alert("Should not fire")}>
            Disabled (no-op)
          </CButton>
        </Row>
      </Section>

      {/* ── 21. LOADING DOES NOT FIRE ───────────────────────────── */}
      <Section title="21. loading — onClick is also suppressed">
        <Row>
          <CButton variant="primary" loading onClick={() => alert("Should not fire")}>
            Loading (no-op)
          </CButton>
        </Row>
      </Section>

      {/* ── 22. NATIVE EVENT OBJECT ─────────────────────────────── */}
      <Section title="22. onClick — access native MouseEvent">
        <Row>
          <CButton
            variant="neutral"
            onClick={(e: React.MouseEvent<HTMLElement>) => {
              setEventLog(`clientX: ${e.clientX}, clientY: ${e.clientY}`);
            }}
          >
            Click to log coords
          </CButton>
          <span style={{ fontSize: "0.85rem", color: "#555" }}>{eventLog}</span>
        </Row>
      </Section>

      {/* ── 23. CONDITIONAL VARIANT SWAP ────────────────────────── */}
      <Section title="23. onClick — conditionally swap variant">
        <Row>
          <CButton variant={danger ? "danger" : "warning"} onClick={() => setDanger((d) => !d)}>
            {danger ? "🔴 Danger mode" : "🟡 Warning mode"} — click to toggle
          </CButton>
        </Row>
      </Section>

      {/* ── 24. GUARDED LINK CLICK ──────────────────────────────── */}
      <Section title="24. onClick on a link button — guard navigation">
        <Row>
          <CButton
            href="https://example.com"
            target="_blank"
            variant="primary"
            onClick={(e: React.MouseEvent<HTMLElement>) => {
              const go = window.confirm("Leave this page?");
              if (!go) e.preventDefault();
            }}
          >
            <span slot="prefix">↗</span>
            Guarded external link
          </CButton>
        </Row>
      </Section>

      {/* ── 25. cFocus / cBlur EVENTS ───────────────────────────── */}
      <Section title="25. cFocus / cBlur events">
        <Row>
          <CButton
            variant="primary"
            onCFocus={() => setEventLog("cFocus fired")}
            onCBlur={() => setEventLog("cBlur fired")}
          >
            Focus / Blur me
          </CButton>
          <span style={{ fontSize: "0.85rem", color: "#555" }}>{eventLog}</span>
        </Row>
      </Section>

      {/* ── 26. IMPERATIVE METHODS VIA REF ──────────────────────── */}
      <Section title="26. Imperative methods via ref">
        <Row>
          <CButton
            ref={focusTargetRef}
            variant="primary"
            onCFocus={() => setEventLog("cFocus fired")}
            onCBlur={() => setEventLog("cBlur fired")}
          >
            Focus target
          </CButton>
          <CButton variant="neutral" onClick={() => (focusTargetRef.current as any)?.setFocus()}>
            setFocus()
          </CButton>
          <CButton variant="neutral" onClick={() => (focusTargetRef.current as any)?.removeFocus()}>
            removeFocus()
          </CButton>
          <CButton variant="neutral" onClick={() => (focusTargetRef.current as any)?.triggerClick()}>
            triggerClick()
          </CButton>
          <span style={{ fontSize: "0.85rem", color: "#555" }}>{eventLog}</span>
        </Row>
      </Section>

      {/* ── 27. COMBINED COMBOS ─────────────────────────────────── */}
      <Section title="27. Combined combos">
        <Row>
          <CButton
            variant="primary" pill caret size="large"
            onClick={() => setClickLog("Deploy clicked!")}
          >
            <span slot="prefix">🚀</span>
            Deploy
          </CButton>

          <CButton variant="danger" outline pill size="small" loading>
            Deleting…
          </CButton>

          <CButton
            variant="success" circle size="large"
            tooltip="Approve this item"
            onClick={() => setClickLog("Approved!")}
          >
            ✓
          </CButton>

          <CButton variant="neutral" outline caret size="small" disabled>
            Options
          </CButton>

          <CButton
            href="https://example.com" target="_blank"
            variant="primary" pill
            onClick={(e: React.MouseEvent<HTMLElement>) => {
              const go = window.confirm("Leave?");
              if (!go) e.preventDefault();
            }}
          >
            <span slot="prefix">↗</span>
            External
            <span slot="suffix">★</span>
          </CButton>

          <span style={{ fontSize: "0.85rem", color: "#555" }}>{clickLog}</span>
        </Row>
      </Section>
    </main>
  );
}
